version: '3.7'

services:

  fruitpicker:
    container_name: fruitpicker
    build:
      context: .
      dockerfile: Dockerfile
    command: [ 'sh', 'run_prod.sh' ]
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "1996:1996"
      - "9266:9266"
    stdin_open: true
    tty: true
