version: '3.7'

services:

  fruitpicker:
    container_name: fruitpicker
    build:
      context: .
      dockerfile: Dockerfile
    command: [ 'sh', 'run_prod.sh' ]
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://host.docker.internal:5566/api/v1/health || exit 1" ]
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5566:5566"
      - "9266:9266"
    volumes:
      - /sys:/sys:ro
    stdin_open: true
    tty: true
